[book]
authors = ["Ahmetcan Aksu"]
language = "en"
multilingual = true
src = "src"
title = "EllieDocs"
description = "Documentation for the Ellie Programming Language"

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/behemehal/EllieDocs"
git-repository-icon = "fa-github"
site-url = "/EllieDocs/"